Update changed_organization.html
ckan/ckan pull request #5985
Opened 2021-03-24 15:27 UTC by Gauravp-NEC

Fix for Issue 5771

Fixes #5771 

### Proposed fixes:

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

2021-04-05 03:06 UTC, Gauravp-NEC commented
@Zharktas , Please review this PR. Thankyou :)

2021-04-13 10:02 UTC, Gauravp-NEC commented
@Zharktas , Please review this PR as it is open for a long time.

2021-04-15 12:01 UTC, Gauravp-NEC commented
@Zharktas , Please review this PR as it is open for a long time.

2021-04-20 05:05 UTC, Zharktas requested changes
@Gauravp-NEC seems mostly fine. url_for's should use named_routes instead of controller/action parameters as controllers are soon removed. Custom fields are shown on the changes view, these should be added, they are named extras in the code. The name of the template organization/organization_changes.html could be just organization/changes.html.

2021-04-20 05:05 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/description.html
> +                pkg_url = h.url_for(controller='organization',
Should be url_for to named route instead on controller/action as controllers are soon removed. See https://github.com/ckan/ckan/blob/abfda8b401ec370c9c74fc67678dcb38f8c72a26/ckan/templates/snippets/changes/notes.html#L14

2021-04-20 05:05 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/description.html
> +              pkg_url = h.url_for(controller='organization',
Should use named route also here.

2021-04-20 05:05 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/image_url.html
> +              pkg_image_url = h.url_for(controller='organization',
Needs named_route.

2021-04-20 05:05 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/image_url.html
> +              pkg_image_url = h.url_for(controller='organization',
Needs named_route

2021-04-20 05:05 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/image_url.html
> +              pkg_image_url = h.url_for(controller='organization',
Needs named_route

2021-04-20 05:05 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/title.html
> +            new_url = h.url_for(controller='organization', action='read', id=change.id),
Needs named_route

2021-04-20 10:22 UTC, Gauravp-NEC commented
@Zharktas, I have done rework in commit  https://github.com/ckan/ckan/pull/5985/commits/ba23409ba8184ca112e0a60bf98cdf8e6dc3530d. If it looks good please merge this PR. Thankyou

2021-04-21 04:59 UTC, Zharktas requested changes
Variable names are a minor thing.

But if you could add those custom field via extras to changes view, this would be good to merge. 

Now if you only update custom fields, you get changes link in activity list but the view doesn't show that anything changed.

2021-04-21 04:59 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/description.html
> +      {{ _('Updated description of {pkg_link} from <br class="line-height2"><blockquote>{old_description}</blockquote> to <br class="line-height2"><blockquote>{new_description}</blockquote>').format(
pkg_link could be renamed to org_link for clarity.

2021-04-21 04:59 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/description.html
> +      {{ _('Updated description of {pkg_link} to <br class="line-height2"><blockquote>{new_description}</blockquote>').format(
pkg_link could be renamed to org_link for clarity.

2021-04-21 04:59 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/description.html
> +      {{ _('Removed description from {pkg_link}').format(
pkg_link could be renamed to org_link for clarity.

2021-04-21 04:59 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/image_url.html
> +      {{ _('Changed the image URL of {pkg_link} from {old_link} to {new_link}').format(
pkg_link could be renamed to org_link for clarity.

2021-04-21 04:59 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/image_url.html
> +      {{ _('Removed the image URL from {pkg_link}').format(
pkg_link could be renamed to org_link for clarity.

2021-04-21 04:59 UTC, Zharktas commented on ckan/templates/snippets/organization_changes/image_url.html
> +      {{ _('Changed the image URL of {pkg_link} to {new_link}').format(
pkg_link could be renamed to org_link for clarity.

2021-04-21 05:58 UTC, Gauravp-NEC commented
@Zharktas , I have changed the "pkg_link" to "org_link" in commit https://github.com/ckan/ckan/pull/5985/commits/c98370b4991e5ac798879420fc77dab366d9f864.

2021-04-22 04:53 UTC, Zharktas reviewed
group_type should be used so that the code doesn't need to be duplicated for groups.

2021-04-22 04:53 UTC, Zharktas commented on ckan/views/group.py
> +    current_group_dict = get_action(u'organization_show')(
This should use group_type as part  of the action call.
```suggestion
    current_group_dict = get_action(group_type + u'_show')(
```

2021-04-22 04:53 UTC, Zharktas commented on ckan/views/group.py
> +    group_activity_list = get_action(u'organization_activity_list')(
```suggestion
    group_activity_list = get_action(group_type + u'_activity_list')(
```

2021-04-22 04:53 UTC, Zharktas commented on ckan/views/group.py
> +    re-renders organization_changes.html with the list.
```suggestion
    re-renders changes.html with the list.
```

2021-04-22 04:53 UTC, Zharktas commented on ckan/views/group.py
> +    current_group_dict = get_action(u'organization_show')(
```suggestion
    current_group_dict = get_action(group_type + u'_show')(
```

2021-04-22 04:53 UTC, Zharktas commented on ckan/views/group.py
> +    group_activity_list = get_action(u'organization_activity_list')(context, {
```suggestion
    group_activity_list = get_action(group_type + u'_activity_list')(context, {
```

2021-04-22 05:14 UTC, Gauravp-NEC commented
@Zharktas , Please merge this PR if it looks good. Thankyou

2021-04-22 05:17 UTC, Zharktas approved these changes

2021-04-22 05:25 UTC, merged