Update read.html
ckan/ckan pull request #6041
Opened 2021-04-22 07:52 UTC by Gauravp-NEC

Fixes #5904 

### Proposed fixes:

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

2021-04-23 06:33 UTC, Gauravp-NEC commented
@amercader , Please review this PR.

2021-04-29 12:08 UTC, Gauravp-NEC commented
@amercader , Please review this PR. Thankyou.

2021-05-04 11:03 UTC, Gauravp-NEC commented
@amercader ,Gentle reminder. Please review this PR. If it looks good please merge this PR. Thankyou.

2021-05-05 08:21 UTC, amercader requested changes

2021-05-05 08:21 UTC, amercader commented on ckan/templates/package/read.html
> +          To see the current version, click <a href="{{ url }}">here</a>.
```suggestion
          You're currently viewing an old version of this dataset.
          Data files may not match the old version of the metadata.
          <a href="{{ url }}">View the current version</a>.
```

2021-05-05 08:21 UTC, amercader commented on ckan/templates/package/resource_read.html
> +                To see the current version, click <a href="{{ url }}">here</a>.
```suggestion
          You're currently viewing an old version of this dataset.
          Data files may not match the old version of the metadata.
          <a href="{{ url }}">View the current version</a>.
```
```

2021-05-05 09:09 UTC, Gauravp-NEC commented
@amercader , based on your suggestion I have done the rework. Now this PR is ready to be merged. Thankyou :)

2021-05-05 11:05 UTC, merged