DataPusher and XLoader documented in Source docs
ckan/ckan pull request #6281
Opened 2021-07-26 08:31 UTC by Gauravp-NEC

Fixes #6269 

### Proposed fixes:
DataStore and XLoader are documented in CKAN source installing document.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

2021-07-28 10:00 UTC, Gauravp-NEC commented
@kowh-ai , Please review this PR. If it looks good please merge it. Thankyou :)

2021-07-28 13:23 UTC, kowh-ai requested changes
I think this reads a bit better

2021-07-28 13:23 UTC, kowh-ai commented on doc/maintaining/installing/install-from-source.rst
>  ---------------
Once you have set up the DataStore, you may then wish to configure either the DataPusher _or_ XLoader extensions to add data to the DataStore. To install DataPusher refer to this link: https://github.com/ckan/datapusher or refer to this link: https://github.com/ckan/ckanext-xloader to install XLoader.

2021-07-28 14:09 UTC, Gauravp-NEC commented
@kowh-ai , Based on your above suggestion I have done the minor rework. Please review it. Thankyou : )

2021-07-29 09:34 UTC, Gauravp-NEC commented
@kowh-ai , Based on your above suggestion I have done the rework. Now this PR is ready to merged. Please review it. Thankyou : )

2021-07-29 11:31 UTC, kowh-ai approved these changes
Looks good - thanks

2021-07-29 11:37 UTC, Gauravp-NEC commented
@kowh-ai , Thankyou for reviewing this PR. Please merge this PR :)

2021-07-29 12:04 UTC, kowh-ai commented
> @kowh-ai , Thankyou for reviewing this PR. Please merge this PR :)

I don't have enough access to merge into the CKAN repo - sorry

2021-07-29 12:07 UTC, Gauravp-NEC commented
@amercader , This PR is approved by @kowh-ai. Please merge this PR. Thankyou :)

2021-07-29 15:45 UTC, merged