Bootstrap 5 migration
ckan/ckan pull request #6307
Opened 2021-08-04 06:44 UTC by sagarggh

Fixes #
 #6012 
### Proposed fixes:
Bootstrap  upgrade  5 

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

2021-08-31 10:51 UTC, amercader commented
@sagargg It's so great to see progress here. How are you getting on with this? Do you need any support from the tech team or other devs?

2021-10-04 02:11 UTC, sagargg commented
Hi @amercader, I think most of the things are done and ready for review. Currenlty  I'm checking the leftover broken item and fixing it.  Also, there are 97 tests failing now and it seems that most of them are not related to these changes.

2021-10-12 16:56 UTC, Zharktas commented
@sagargg now the failing tests should be related to this PR, they mostly contain tests that look for specific HTML.

2021-11-30 14:04 UTC, pdelboca commented
This is a massive work @sagargg , thanks for pulling it together!

I have been reviewing and found some things in the UI that may need a few tweaks.

1. Buttons to add new resources (or images) seems off: 
![image](https://user-images.githubusercontent.com/6672339/144061041-3d0b3be7-1b43-4011-8ffe-f3560c54919a.png)

2. Flask-DebugToolbar div seems off too:
![image](https://user-images.githubusercontent.com/6672339/144061199-3b3de729-7e82-43f4-a428-983296f435ca.png)

3. Home page seems to have an issue sticking the footer to the bottom of the page:
![image](https://user-images.githubusercontent.com/6672339/144061389-75d630ad-37a8-4d14-a119-8c2d672cab7a.png)


This errors seems minor but it worth be good to take a look at them and make an action plan to merge this before other PRs can introduce massive changes to templates.

cc @ckan/core

2021-12-16 14:22 UTC, pdelboca commented
@sagargg it would be nice to not let die this effort and do a little bit more so we can merge it for the next patch release `2.10.0` in January.

In order to do it we need to:
- Add a mechanism to support BS3 and BS5
- Test that it's compatible to run CKAN in both
- Merge this changes into master

## How to support BS3 and BS5

We did it before when migrating BS2 to BS3. Basically we need to:
- Maintain folders for BS3 (This is already done in the PR with `templates-bs3` and `public-bs3`)
- Update [here](https://github.com/ckan/ckan/blob/9d262b5a156ff1f947618df2b261eca79f77f78d/ckan/config/environment.py#L38-L46) and [here](https://github.com/ckan/ckan/blob/9d262b5a156ff1f947618df2b261eca79f77f78d/ckan/config/environment.py#L188-L197) to allow use of BS3 templates.

## How to test for BS3 compatibility
- Add needed configurations in `ckan.ini` file: 
  - `ckan.base_public_folder=public-bs3`
  - `ckan.base_templates_folder=templates-bs3`
- Run CKAN

@sagargg from an initial test it's not working properly when trying to update to BS3. Do you have time to work on this PR between now and January? If so it would be awesome so we can add this work to `2.10.0`.

Let me know if you have time to work on this PR! (I can support you with whatever you need)

cc @ckan/core

2021-12-16 14:25 UTC, pdelboca commented
Also it's worth considering that `ckanext-scheming` is a heavy use of `panels` that are deprecated in BS5. However since the release schedule is different from CKAN it's okay to merge BS5 if we can keep compatibility to BS3.

2021-12-23 03:46 UTC, sagargg commented
Hi @pdelboca, thanks for providing the review feedbacks.  I made changes to support both BS3 and BS4 templates. Also fixed styling from the above comment.

2022-01-03 12:43 UTC, pdelboca commented
Hi @sagargg ! Sorry for the delay on answering (holidays). Thanks for the update, now I can run in `bs3` and `bs5` without failing.

There are still some things to address:

### BS 5
 - The `Upload` button on the resource create page doesn't trigger any action
 
![upload button](https://user-images.githubusercontent.com/6672339/147931802-d749edff-2a22-42a1-9651-fbd27b640e95.gif)


### BS3
Even when the system can run there are some components of the UI broken:
 - The navbar is not displayed correctly (Logo on the rigth and the navigation links are not render properly)
 - The organization grid is broken when uploading an Organization image
 
 The following screenshot provides an example of both the points mentioned:
 
![image](https://user-images.githubusercontent.com/6672339/147931565-3afafad5-ae67-4d5c-a7eb-88044f9487b4.png)

2022-01-04 04:58 UTC, sagargg commented
@pdelboca  That should be fixed now. Let me know if you found other issues.

2022-01-19 14:18 UTC, amercader commented
@sagargg @pdelboca I've merged https://github.com/ckan/ckan/pull/6227 which will probably mean some work here to adapt it, but unless you think otherwise I think it's better to handle it in a separate PR.

(@wardi I wonder if it makes sense to add the new resource upload snippets just to the new default Boostrap 5 templates and leave the BS 3 with the current snippets. Or will that complicate things?)

So let's merge this and create a followup issue with pending tasks like the one above. To get this merged let's look at why the checks are failing and fix the conflicts.

Thanks!

2022-01-19 20:08 UTC, wardi commented
@amercader I think it's better to have it in both because it's kind of strange to require bs5 for custom url types in resources. Is there a technical reason why this would be difficult?

2022-02-05 03:11 UTC, sagargg commented
Hi @pdelboca  @amercader,  What is blocking here to merge this PR?

2022-02-05 08:44 UTC, Zharktas commented
@sagargg it's mostly time constraints, I'll intend to have some final review of this hopefully next week.

2022-02-07 07:55 UTC, Zharktas commented
When bs3-templates are used, it loads the wrong base directory, it still uses public instead of public-bs3 which results broken UI's.
Additionally the trash in ckan-admin seems to be broken on bs5 templates.

![image](https://user-images.githubusercontent.com/830663/152747220-fa17a2b3-c135-4164-8ab1-70d4971f5c18.png)

In above image, there should be deleted dataset shown.

![image](https://user-images.githubusercontent.com/830663/152747313-f152b5cb-e79e-49e6-8a26-710659b7d298.png)

2022-02-08 13:40 UTC, Zharktas commented
We discussed this on the dev meeting and once the bs3 templates use bs3 javascript files, this can be merged, rest of the issues can be fixed later on as the next ckan release is not scheduled yet.

2022-02-09 15:55 UTC, sagargg commented
@Zharktas  could you double check please. bs3 resources are loading for me. 
```
ckan.base_public_folder=public-bs3
ckan.base_templates_folder=templates-bs3
```

2022-02-09 16:35 UTC, sagargg commented
@Zharktas  fixed broken UI in admin trash page.

2022-02-09 16:40 UTC, Zharktas commented
Bah, there where two different settings, which I don't like very much but that's how it was previously in similar migration so no need to change that. Can you update the error messages to contain valid options [here](https://github.com/ckan/ckan/blob/fd2a5e1a0eaeb3c93215bbf87e4938ed2313af2e/ckan/config/environment.py#L42-L45) and [here](https://github.com/ckan/ckan/blob/fd2a5e1a0eaeb3c93215bbf87e4938ed2313af2e/ckan/config/environment.py#L193-L197) and add a changelog entry in `changes/6307.feature` file, then were good to go.

2022-02-10 10:52 UTC, sagargg commented
@Zharktas  Done.

2022-02-11 07:10 UTC, Zharktas requested changes
Just a minor thing to fix and then I'll merge this :)

2022-02-11 07:10 UTC, Zharktas commented on ckan/config/environment.py
> +            'Possible values are: "public-bs3".'
```suggestion
            'Possible values are: "public" and "public-bs3".'
```

2022-02-11 07:10 UTC, Zharktas commented on ckan/config/environment.py
> +            'Possible values are: "templates-bs3".'
```suggestion
            'Possible values are: "templates" and "templates-bs3".'
```

2022-02-11 12:02 UTC, merged

2022-02-11 13:21 UTC, pdelboca commented
This is a great work @sagargg ! Thank you so much for this PR :)

And thanks @Zharktas for following up and merging it.

2022-02-11 14:05 UTC, amercader commented
:tada: Thanks @sagargg for the hard work and @Zharktas for the review!