fix engine none object error
ckan/ckan pull request #8448
Opened 2024-09-20 10:05 UTC by Nisha1293

Fixes #8447 

### Proposed fixes:

Fix None Type engine object error.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

2024-09-24 13:36 UTC, tino097 requested changes

2024-10-09 10:16 UTC, Nisha1293 commented on ckanext/tracking/middleware.py
> +        # Check if the engine is initialized
Hi @tino097 Are you referring to the ckan/migrations/versions/057_660a5aae527e_tracking.py.
As my understanding, the tables for tracking extension are created from the core migration.

2024-10-09 10:26 UTC, tino097 commented on ckanext/tracking/middleware.py
> +        # Check if the engine is initialized
@Nisha1293 i was pointing to [this](https://github.com/ckan/ckan/wiki/CKAN-2.10-to-2.11-migration-tips#table-object-xx-is-not-bound-to-an-engine-or-connection) 
The stats models are not using the BaseModel and with 2.11 changes, `engine` will be always `None` and the insertion in the tracking tables never happens

2024-10-12 19:44 UTC, tino097 commented
Closing in favor of #8479 

@Nisha1293 this is a critical issue and we need to react faster as migrating to 2.11 will cause tracking issues with existing portals. 
Please check this PR changes and report if you find any other issues

2024-10-12 19:44 UTC, closed without merging